CREATE TABLE [dbo].[Order]
(
	[OrderID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [State] VARCHAR(50) NOT NULL, 
    [BookID] INT NOT NULL, 
    [Quantity] INT NOT NULL, 
    [ExpDate] DATE NULL, 
    [Email] NVARCHAR(256) NOT NULL, 
    [Name] NVARCHAR(256) NOT NULL, 
    [Address] NVARCHAR(256) NOT NULL, 
    CONSTRAINT [FK_Order_ToBook] FOREIGN KEY ([BookID]) REFERENCES [Book]([BookID]) ON DELETE CASCADE
)
